### ISSUE TITLE
Detection isn't handled amazingly

### ISSUE THREAD

**Issue by Arimzon** [confusinguser/Melody-Mod#1] opened 2020-01-13 01:59 UTC
In my understand Keyboard.getEventKey in the listener would trigger both when the key is pressed down but also when the key is released as two separate events. Maybe something like !Keyboard.isRepeatEvent() could help?

**Comment by confusinguser** [comment] 2020-03-06 17:46
I'm going to try and fix this issue with `!Keyboard.isRepeatEvent()` and maybe some other solutions

**Comment by confusinguser** [comment] 2020-03-07 10:20
The issue is now fixed. I fixed it by storing the key's state last tick and only activating if the key wasn't pressed last tick but now is.

**Closed as completed by confusinguser** 2020-03-07 10:20 UTC
Labels: bug
